name: a02_HdD
on:
  workflow_dispatch:
jobs:
  Mi_inicio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "varios"
        run:
          git config user.name "jhassir-commit"
          git config user.email "aleksander19120@gmail.com"
          echo "<p>bien<p> >> index.html
          git add .
          git commit -m "automatico"
          git push origin main
